In [1]:
import streamlit as st
import pandas as pd
import pydeck as pdk
import hashlib
import glob
import streamlit.components.v1 as components
import plotly.graph_objects as go
import matplotlib.colors as mcolors
from parso.pgen2.generator import DFAPlan

In [2]:
# 📂 Ruta donde están los archivos
ruta_archivos = "reportes_clientes/*.xlsx"

# 🧾 Lista de todos los archivos que coincidan
archivos = glob.glob(ruta_archivos)

# 📊 Leer y concatenar todos los archivos (solo hoja 'Resumen ruta')
dfs = []

for archivo in archivos:
    try:
        df_temp = pd.read_excel(archivo, sheet_name="Reporte diario cliente")
        df_temp["Archivo"] = archivo  # opcional: para saber de qué archivo viene
        dfs.append(df_temp)
    except ValueError:
        print(f"⚠️ La hoja 'Resumen ruta' no se encontró en {archivo}")
    except Exception as e:
        print(f"❌ Error al leer {archivo}: {e}")

# Concatenar si hay data
if dfs:
    df_mrk = pd.concat(dfs, ignore_index=True)
    print("✅ Archivos combinados correctamente:", len(dfs))
else:
    print("⚠️ No se pudo leer ningún archivo válido.")

✅ Archivos combinados correctamente: 42

In [3]:
df_mrk

,Zona,Región,Gerencia,Jefatura,Ruta,Id cliente,Cliente,Canal,GEC,Fecha,...,Latitud del maestro,Longitud del maestro,Tiempo de atencion,Geoeficiencia fuera de frecuencia,Geoefectividad fuera de frecuencia,Fuera de frecuencia,Pedido Digital,Pedido Omnicanal,Planeado Digital,Archivo
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,0.000000,0.000000,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,0.000000,0.000000,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,0.000000,0.000000,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,0.000000,0.000000,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,0.000000,0.000000,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449290,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0197,1950084073,AMBURGUEZAS DON PACO,RSR TACOS,BRONCE,2025-06-05,...,17.135705,-99.375163,00:02:24,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-06-01...
11449291,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0199,1950084082,TEN MATA,HOGAR CON VENTA,BRONCE,2025-06-05,...,16.972676,-99.319493,00:00:03,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-06-01...
11449292,CENTRO-PACIFICO,ACAPULCO,CJ01,CJ2,CJ0011,1950084121,REST LORE,FONDAS Y RESTAURANTES,BRONCE,2025-06-07,...,16.797624,-99.836408,00:05:18,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-06-01...
11449293,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084104,ABTS AMBAR,HOGAR CON VENTA,BRONCE,2025-06-07,...,17.552723,-99.508380,00:10:53,1,1,0,1,1,1,reportes_clientes/IndicadoresReport_2025-06-01...
11449294,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084124,DONA LETY,HOGAR CON VENTA,BRONCE,2025-06-07,...,17.556405,-99.501983,00:00:31,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-06-01...

In [4]:
from datetime import time

# 🕒 1. Detectar columnas con "(hr)"
cols_hr = [col for col in df_mrk.columns if '(hr)' in col]
print("Columnas a convertir:", cols_hr)

# 🧭 2. Normalizar y convertir
for col in cols_hr:
    # Si algún valor es datetime.time, conviértelo a string "HH:MM:SS"
    df_mrk[col] = df_mrk[col].apply(
        lambda x: x.strftime('%H:%M:%S') if isinstance(x, time) else x
    )
    # Luego convertir a timedelta
    df_mrk[col] = pd.to_timedelta(df_mrk[col], errors='coerce')

# 📊 Verificar
df_mrk.info()

Columnas a convertir: []
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11449295 entries, 0 to 11449294
Data columns (total 31 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   Zona                                   object
 1   Región                                 object
 2   Gerencia                               object
 3   Jefatura                               object
 4   Ruta                                   object
 5   Id cliente                             int64
 6   Cliente                                object
 7   Canal                                  object
 8   GEC                                    object
 9   Fecha                                  datetime64[ns]
 10  Pedido                                 int64
 11  Distancia de llegada al cliente (mts)  float64
 12  Distancia de salida al cliente (mts)   float64
 13  Hora de llegada                        object
 14  Hora de salida                         object
 15  Geoeficiencia                          int64
 16  Geoefectividad                         int64
 17  Latitud de entrada                     float64
 18  Longitud de entrada                    float64
 19  Latitud de salida                      float64
 20  Longitud de salida                     float64
 21  Latitud del maestro                    float64
 22  Longitud del maestro                   float64
 23  Tiempo de atencion                     object
 24  Geoeficiencia fuera de frecuencia      int64
 25  Geoefectividad fuera de frecuencia     int64
 26  Fuera de frecuencia                    int64
 27  Pedido Digital                         int64
 28  Pedido Omnicanal                       int64
 29  Planeado Digital                       int64
 30  Archivo                                object
dtypes: datetime64[ns](1), float64(8), int64(10), object(12)
memory usage: 2.6+ GB

In [5]:
df_mrk.head()

,Zona,Región,Gerencia,Jefatura,Ruta,Id cliente,Cliente,Canal,GEC,Fecha,...,Latitud del maestro,Longitud del maestro,Tiempo de atencion,Geoeficiencia fuera de frecuencia,Geoefectividad fuera de frecuencia,Fuera de frecuencia,Pedido Digital,Pedido Omnicanal,Planeado Digital,Archivo
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,0.0,0.0,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,0.0,0.0,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,0.0,0.0,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,0.0,0.0,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,0.0,0.0,00:00:00,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...

In [6]:
df_catalogo = pd.read_csv('catalogo.csv', encoding='utf-8')
df_catalogo = df_catalogo[['Ruta','Jefatura','Tipo','Descripción Tipo','TPV','Región Comercial_Act 2026','Nombre UO']]

df_mrk_full = df_mrk.merge(how='left', right=df_catalogo, left_on='Ruta', right_on='Ruta')
df_mrk_full.head()

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente,Canal,GEC,Fecha,...,Pedido Digital,Pedido Omnicanal,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,0,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco

In [7]:
df_mrk_cp = df_mrk_full[df_mrk_full['Zona'] == 'CENTRO-PACIFICO']
df_mrk_cp = df_mrk_cp[df_mrk_cp['Tipo'].isin(['PR', 'PCOP', 'FC', 'MA', 'PRTDC'])]
df_mrk_cp = df_mrk_cp.rename(columns={'Fecha': 'Fecha inicio'})

df_mrk_cp['Región'] = df_mrk_cp['Región'].where(
~df_mrk_cp['Tipo'].isin(['MA', 'PRTDC'])
).fillna(df_mrk_cp['Tipo'].replace({'MA': 'MAYORISTAS', 'PRTDC': 'MODERNO'}))
df_mrk_cp['Semana'] = df_mrk_cp['Fecha inicio'].dt.isocalendar().week

df_mrk_cp

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente,Canal,GEC,Fecha inicio,...,Pedido Omnicanal,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,5
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449290,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0197,1950084073,AMBURGUEZAS DON PACO,RSR TACOS,BRONCE,2025-06-05,...,1,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23
11449291,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0199,1950084082,TEN MATA,HOGAR CON VENTA,BRONCE,2025-06-05,...,0,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23
11449292,CENTRO-PACIFICO,ACAPULCO,CJ01,CJ2,CJ0011,1950084121,REST LORE,FONDAS Y RESTAURANTES,BRONCE,2025-06-07,...,1,1,reportes_clientes/IndicadoresReport_2025-06-01...,CJ1,PR,Preventa Comercial,ZPV,Acapulco,Cayaco,23
11449293,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084104,ABTS AMBAR,HOGAR CON VENTA,BRONCE,2025-06-07,...,1,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23
11449294,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084124,DONA LETY,HOGAR CON VENTA,BRONCE,2025-06-07,...,0,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23

In [8]:
df_mrk_cp['Tiempo de atencion'] = pd.to_timedelta(df_mrk_cp['Tiempo de atencion'], errors='coerce')
df_mrk_cp['Hora de llegada'] = pd.to_datetime(
    df_mrk_cp['Hora de llegada'], format='%H:%M:%S', errors='coerce'
)

# 📊 Crear el pivot con diferentes funciones de agregación
df_pivot_gec = df_mrk_cp.pivot_table(
    index=['Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','Fecha inicio','GEC'],
    aggfunc={
        'Id cliente': 'count',
        'Geoeficiencia': 'sum',
        'Geoefectividad': 'sum',
        'Tiempo de atencion': 'mean',
        'Hora de llegada': 'min',
        'Pedido Omnicanal': 'sum',
    }
)

# 🔹 Convertir timedelta a HH:MM:SS sin días ni decimales
#df_pivot_gec['Tiempo de atencion'] = df_pivot_gec['Tiempo de atencion'].apply(
#    lambda x: str(x).split(' days ')[-1].split('.')[0] if pd.notnull(x) else None
#)

# 🔹 Mostrar solo HH:MM:SS en la hora de llegada
df_pivot_gec['Hora de llegada'] = df_pivot_gec['Hora de llegada'].dt.strftime('%H:%M:%S')

df_pivot_gec

                                                                                                      Geoefectividad  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE                   15
                                                                                         CUSTOMIZADO               3
                                                                                         ORO                      11
                                                                                         PLATA                    18
                                                                            2025-01-03   BRONCE                    4
...                                                                                                              ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-07   CUSTOMIZADO              11
                                                                            2025-11-08   CUSTOMIZADO               3
                                                                            2025-11-10   CUSTOMIZADO               7
                                                                            2025-11-11   CUSTOMIZADO               5
                                                                            2025-11-12   CUSTOMIZADO               7

                                                                                                      Geoeficiencia  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE                  27
                                                                                         CUSTOMIZADO              4
                                                                                         ORO                     14
                                                                                         PLATA                   32
                                                                            2025-01-03   BRONCE                  30
...                                                                                                             ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-07   CUSTOMIZADO             12
                                                                            2025-11-08   CUSTOMIZADO              3
                                                                            2025-11-10   CUSTOMIZADO              9
                                                                            2025-11-11   CUSTOMIZADO              7
                                                                            2025-11-12   CUSTOMIZADO              9

                                                                                                     Hora de llegada  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE             10:37:28
                                                                                         CUSTOMIZADO        10:32:08
                                                                                         ORO                10:07:36
                                                                                         PLATA              10:47:29
                                                                            2025-01-03   BRONCE             08:27:25
...                                                                                                              ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-07   CUSTOMIZADO        07:34:12
                                                                            2025-11-08   CUSTOMIZADO        08:41:12
                                                                            2025-11-10   CUSTOMIZADO        08:34:42
                                                                            2025-11-11   CUSTOMIZADO        08:06:29
                                                                            2025-11-12   CUSTOMIZADO        08:19:26

                                                                                                      Id cliente  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE               29
                                                                                         CUSTOMIZADO           4
                                                                                         ORO                  15
                                                                                         PLATA                32
                                                                            2025-01-03   BRONCE               38
...                                                                                                          ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-07   CUSTOMIZADO          12
                                                                            2025-11-08   CUSTOMIZADO           4
                                                                            2025-11-10   CUSTOMIZADO          10
                                                                            2025-11-11   CUSTOMIZADO           9
                                                                            2025-11-12   CUSTOMIZADO           9

                                                                                                      Pedido Omnicanal  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE                     16
                                                                                         CUSTOMIZADO                 3
                                                                                         ORO                        12
                                                                                         PLATA                      20
                                                                            2025-01-03   BRONCE                      6
...                                                                                                                ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-07   CUSTOMIZADO                11
                                                                            2025-11-08   CUSTOMIZADO                 4
                                                                            2025-11-10   CUSTOMIZADO                 9
                                                                            2025-11-11   CUSTOMIZADO                 8
                                                                            2025-11-12   CUSTOMIZADO                 8

                                                                                                            Tiempo de atencion
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE      0 days 00:00:40.793103448
                                                                                         CUSTOMIZADO    0 days 00:01:15.750000
                                                                                         ORO         0 days 00:02:17.533333333
                                                                                         PLATA          0 days 00:01:15.875000
                                                                            2025-01-03   BRONCE      0 days 00:00:09.210526315
...                                                                                                                        ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-07   CUSTOMIZADO    0 days 00:07:16.500000
                                                                            2025-11-08   CUSTOMIZADO    0 days 00:06:46.250000
                                                                            2025-11-10   CUSTOMIZADO    0 days 00:08:26.900000
                                                                            2025-11-11   CUSTOMIZADO 0 days 00:08:01.555555555
                                                                            2025-11-12   CUSTOMIZADO           0 days 00:05:14

[672515 rows x 6 columns]

In [9]:
df_pivot_gec = df_pivot_gec.reset_index()
df_pivot_gec.info()
df_pivot_gec

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672515 entries, 0 to 672514
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Región Comercial_Act 2026  672515 non-null  object
 1   Nombre UO                  672515 non-null  object
 2   Jefatura_y                 672515 non-null  object
 3   Ruta                       672515 non-null  object
 4   Descripción Tipo           672515 non-null  object
 5   Fecha inicio               672515 non-null  datetime64[ns]
 6   GEC                        672515 non-null  object
 7   Geoefectividad             672515 non-null  int64
 8   Geoeficiencia              672515 non-null  int64
 9   Hora de llegada            672515 non-null  object
 10  Id cliente                 672515 non-null  int64
 11  Pedido Omnicanal           672515 non-null  int64
 12  Tiempo de atencion         672515 non-null  timedelta64[ns]
dtypes: datetime64[ns](1), int64(4), object(7), timedelta64[ns](1)
memory usage: 66.7+ MB

,Región Comercial_Act 2026,Nombre UO,Jefatura_y,Ruta,Descripción Tipo,Fecha inicio,GEC,Geoefectividad,Geoeficiencia,Hora de llegada,Id cliente,Pedido Omnicanal,Tiempo de atencion
0,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,BRONCE,15,27,10:37:28,29,16,0 days 00:00:40.793103448
1,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,CUSTOMIZADO,3,4,10:32:08,4,3,0 days 00:01:15.750000
2,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,ORO,11,14,10:07:36,15,12,0 days 00:02:17.533333333
3,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,PLATA,18,32,10:47:29,32,20,0 days 00:01:15.875000
4,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-03,BRONCE,4,30,08:27:25,38,6,0 days 00:00:09.210526315
...,...,...,...,...,...,...,...,...,...,...,...,...,...
672510,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-07,CUSTOMIZADO,11,12,07:34:12,12,11,0 days 00:07:16.500000
672511,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-08,CUSTOMIZADO,3,3,08:41:12,4,4,0 days 00:06:46.250000
672512,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-10,CUSTOMIZADO,7,9,08:34:42,10,9,0 days 00:08:26.900000
672513,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-11,CUSTOMIZADO,5,7,08:06:29,9,8,0 days 00:08:01.555555555
672514,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-12,CUSTOMIZADO,7,9,08:19:26,9,8,0 days 00:05:14

In [10]:
df_final_cliente = df_pivot_gec[['Fecha inicio','Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','GEC','Id cliente','Geoeficiencia','Geoefectividad','Hora de llegada','Tiempo de atencion','Pedido Omnicanal']]

df_final_cliente = df_final_cliente.rename(columns={'Jefatura_y': 'Jefatura'})

df_final_cliente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672515 entries, 0 to 672514
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fecha inicio               672515 non-null  datetime64[ns]
 1   Región Comercial_Act 2026  672515 non-null  object
 2   Nombre UO                  672515 non-null  object
 3   Jefatura                   672515 non-null  object
 4   Ruta                       672515 non-null  object
 5   Descripción Tipo           672515 non-null  object
 6   GEC                        672515 non-null  object
 7   Id cliente                 672515 non-null  int64
 8   Geoeficiencia              672515 non-null  int64
 9   Geoefectividad             672515 non-null  int64
 10  Hora de llegada            672515 non-null  object
 11  Tiempo de atencion         672515 non-null  timedelta64[ns]
 12  Pedido Omnicanal           672515 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(7), timedelta64[ns](1)
memory usage: 66.7+ MB

In [11]:
df_final_cliente.to_parquet('bdd_mrk_cp_gec.parquet')

In [12]:
df_mrk_cp

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente,Canal,GEC,Fecha inicio,...,Pedido Omnicanal,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,5
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,0,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449290,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0197,1950084073,AMBURGUEZAS DON PACO,RSR TACOS,BRONCE,2025-06-05,...,1,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23
11449291,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0199,1950084082,TEN MATA,HOGAR CON VENTA,BRONCE,2025-06-05,...,0,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23
11449292,CENTRO-PACIFICO,ACAPULCO,CJ01,CJ2,CJ0011,1950084121,REST LORE,FONDAS Y RESTAURANTES,BRONCE,2025-06-07,...,1,1,reportes_clientes/IndicadoresReport_2025-06-01...,CJ1,PR,Preventa Comercial,ZPV,Acapulco,Cayaco,23
11449293,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084104,ABTS AMBAR,HOGAR CON VENTA,BRONCE,2025-06-07,...,1,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23
11449294,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084124,DONA LETY,HOGAR CON VENTA,BRONCE,2025-06-07,...,0,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23

In [13]:
df_class_clientes = pd.read_csv('Class_Clientes.csv', encoding='utf-8')
df_class_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cliente              444 non-null    int64
 1   Recurrencia Digital  444 non-null    object
dtypes: int64(1), object(1)
memory usage: 7.1+ KB

In [14]:
df_mrk_cp_class = df_mrk_cp.merge(how='left',right=df_class_clientes,left_on='Id cliente',right_on='Cliente')
df_mrk_cp_class = df_mrk_cp_class.drop(columns=['Cliente_y'])
df_mrk_cp_class['Recurrencia Digital'] = df_mrk_cp_class['Recurrencia Digital'].fillna("No")
df_mrk_cp_class

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente_x,Canal,GEC,Fecha inicio,...,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana,Recurrencia Digital
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,5,No
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11335782,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0197,1950084073,AMBURGUEZAS DON PACO,RSR TACOS,BRONCE,2025-06-05,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23,No
11335783,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0199,1950084082,TEN MATA,HOGAR CON VENTA,BRONCE,2025-06-05,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23,No
11335784,CENTRO-PACIFICO,ACAPULCO,CJ01,CJ2,CJ0011,1950084121,REST LORE,FONDAS Y RESTAURANTES,BRONCE,2025-06-07,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,CJ1,PR,Preventa Comercial,ZPV,Acapulco,Cayaco,23,No
11335785,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084104,ABTS AMBAR,HOGAR CON VENTA,BRONCE,2025-06-07,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23,No
11335786,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084124,DONA LETY,HOGAR CON VENTA,BRONCE,2025-06-07,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23,No

In [15]:
# 📊 Crear el pivot con diferentes funciones de agregación
df_pivot_class = df_mrk_cp_class.pivot_table(
    index=['Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','Fecha inicio','Recurrencia Digital'],
    aggfunc={
        'Id cliente': 'count',
        'Geoeficiencia': 'sum',
        'Geoefectividad': 'sum',
        'Tiempo de atencion': 'mean',
        'Hora de llegada': 'min',
        'Pedido Omnicanal': 'sum',
    }
)

# 🔹 Mostrar solo HH:MM:SS en la hora de llegada
df_pivot_class['Hora de llegada'] = df_pivot_class['Hora de llegada'].dt.strftime('%H:%M:%S')
df_pivot_class = df_pivot_class.reset_index()
df_pivot_class

,Región Comercial_Act 2026,Nombre UO,Jefatura_y,Ruta,Descripción Tipo,Fecha inicio,Recurrencia Digital,Geoefectividad,Geoeficiencia,Hora de llegada,Id cliente,Pedido Omnicanal,Tiempo de atencion
0,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,No,45,75,10:07:36,78,49,0 days 00:01:15.692307692
1,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,Si,2,2,12:29:44,2,2,0 days 00:00:36.500000
2,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-03,No,14,66,08:06:30,78,21,0 days 00:00:23.705128205
3,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-03,Si,0,1,08:07:05,2,1,0 days 00:01:56.500000
4,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-04,No,34,55,08:50:54,57,39,0 days 00:01:13.280701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
241860,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-07,No,11,12,07:34:12,12,11,0 days 00:07:16.500000
241861,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-08,No,3,3,08:41:12,4,4,0 days 00:06:46.250000
241862,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-10,No,7,9,08:34:42,10,9,0 days 00:08:26.900000
241863,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-11,No,5,7,08:06:29,9,8,0 days 00:08:01.555555555
241864,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-12,No,7,9,08:19:26,9,8,0 days 00:05:14

In [16]:
df_final_cliente_class = df_pivot_class[['Fecha inicio','Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','Recurrencia Digital','Id cliente','Geoeficiencia','Geoefectividad','Hora de llegada','Tiempo de atencion','Pedido Omnicanal']]

df_final_cliente_class = df_final_cliente_class[df_final_cliente_class['Recurrencia Digital'] == 'Si']
df_final_cliente_class = df_final_cliente_class.rename(columns={'Jefatura_y': 'Jefatura'})

df_final_cliente_class.to_parquet('bdd_mrk_cp_class.parquet')

df_final_cliente_class.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30097 entries, 1 to 241330
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fecha inicio               30097 non-null  datetime64[ns]
 1   Región Comercial_Act 2026  30097 non-null  object
 2   Nombre UO                  30097 non-null  object
 3   Jefatura                   30097 non-null  object
 4   Ruta                       30097 non-null  object
 5   Descripción Tipo           30097 non-null  object
 6   Recurrencia Digital        30097 non-null  object
 7   Id cliente                 30097 non-null  int64
 8   Geoeficiencia              30097 non-null  int64
 9   Geoefectividad             30097 non-null  int64
 10  Hora de llegada            30097 non-null  object
 11  Tiempo de atencion         30097 non-null  timedelta64[ns]
 12  Pedido Omnicanal           30097 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(7), timedelta64[ns](1)
memory usage: 3.2+ MB

In [17]:
df_mrk_cp_class

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente_x,Canal,GEC,Fecha inicio,...,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana,Recurrencia Digital
0,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-01,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,5,No
1,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-08,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
2,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-03,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
3,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-07,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
4,CENTRO-PACIFICO,TECAMACHALCO,NA01,NA6,NA0028,142,DISTRIBUIDORA LA PIEDAD,NaN,NaN,2025-02-05,...,1,reportes_clientes/IndicadoresReport_2025-02-01...,NA6,PR,Preventa Comercial,ZPV,Tecamachalco,Tecamachalco,6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11335782,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0197,1950084073,AMBURGUEZAS DON PACO,RSR TACOS,BRONCE,2025-06-05,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23,No
11335783,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HW01,HW1,HW0199,1950084082,TEN MATA,HOGAR CON VENTA,BRONCE,2025-06-05,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HW1,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Tierra Colorada,23,No
11335784,CENTRO-PACIFICO,ACAPULCO,CJ01,CJ2,CJ0011,1950084121,REST LORE,FONDAS Y RESTAURANTES,BRONCE,2025-06-07,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,CJ1,PR,Preventa Comercial,ZPV,Acapulco,Cayaco,23,No
11335785,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084104,ABTS AMBAR,HOGAR CON VENTA,BRONCE,2025-06-07,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23,No
11335786,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV3,HV0103,1950084124,DONA LETY,HOGAR CON VENTA,BRONCE,2025-06-07,...,1,reportes_clientes/IndicadoresReport_2025-06-01...,HV3,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,23,No

In [18]:
df_mrk_cp_class.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11335787 entries, 0 to 11335786
Data columns (total 39 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   Zona                                   object
 1   Región                                 object
 2   Gerencia                               object
 3   Jefatura_x                             object
 4   Ruta                                   object
 5   Id cliente                             int64
 6   Cliente_x                              object
 7   Canal                                  object
 8   GEC                                    object
 9   Fecha inicio                           datetime64[ns]
 10  Pedido                                 int64
 11  Distancia de llegada al cliente (mts)  float64
 12  Distancia de salida al cliente (mts)   float64
 13  Hora de llegada                        datetime64[ns]
 14  Hora de salida                         object
 15  Geoeficiencia                          int64
 16  Geoefectividad                         int64
 17  Latitud de entrada                     float64
 18  Longitud de entrada                    float64
 19  Latitud de salida                      float64
 20  Longitud de salida                     float64
 21  Latitud del maestro                    float64
 22  Longitud del maestro                   float64
 23  Tiempo de atencion                     timedelta64[ns]
 24  Geoeficiencia fuera de frecuencia      int64
 25  Geoefectividad fuera de frecuencia     int64
 26  Fuera de frecuencia                    int64
 27  Pedido Digital                         int64
 28  Pedido Omnicanal                       int64
 29  Planeado Digital                       int64
 30  Archivo                                object
 31  Jefatura_y                             object
 32  Tipo                                   object
 33  Descripción Tipo                       object
 34  TPV                                    object
 35  Región Comercial_Act 2026              object
 36  Nombre UO                              object
 37  Semana                                 UInt32
 38  Recurrencia Digital                    object
dtypes: UInt32(1), datetime64[ns](2), float64(8), int64(10), object(17), timedelta64[ns](1)
memory usage: 3.3+ GB

In [19]:
# 🧾 Columnas a considerar
columns = [
    'Región Comercial_Act 2026', 'Nombre UO', 'Jefatura_y', 'Ruta', 'Descripción Tipo',
    'Id cliente', 'Cliente_x', 'Recurrencia Digital', 'Canal', 'GEC', 'Fecha inicio',
    'Distancia de llegada al cliente (mts)', 'Distancia de salida al cliente (mts)',
    'Hora de llegada', 'Hora de salida', 'Fuera de frecuencia',
    'Geoeficiencia', 'Geoefectividad', 'Tiempo de atencion', 'Pedido Digital'
]

# 📋 Crear copia del DataFrame base para evitar SettingWithCopyWarning
df_printable = df_mrk_cp_class[columns].copy()

# 🕒 Convertir columnas de hora a datetime con formato explícito
df_printable['Hora de llegada'] = pd.to_datetime(
    df_printable['Hora de llegada'],
    format='%Y-%m-%d %H:%M:%S',
    errors='coerce'
)

# 🕓 Mostrar solo HH:MM:SS
df_printable['Hora de llegada'] = df_printable['Hora de llegada'].dt.strftime('%H:%M:%S')

# ⏱️ Convertir tiempo de atención a formato timedelta
df_printable['Tiempo de atencion'] = pd.to_timedelta(df_printable['Tiempo de atencion'], unit='ms')

# 💻 Filtrar solo los clientes con recurrencia digital
df_printable = df_printable[df_printable['Recurrencia Digital'] == 'Si']

# 🕒 Mostrar solo HH:MM:SS en Tiempo de atención (sin "0 days")
df_printable['Tiempo de atencion'] = df_printable['Tiempo de atencion'].apply(
    lambda x: str(x).split(' days ')[-1].split('.')[0] if pd.notnull(x) else None
)

inicio = '2025-10-01'
fin = '2025-11-15'

df_filtrado = df_printable[
    (df_printable['Fecha inicio'] >= inicio) &
    (df_printable['Fecha inicio'] <= fin)
]

# 📅 Ordenar por Fecha, Región, UO, Jefatura, Ruta y Hora de llegada
df_filtrado = df_filtrado.sort_values(
    by=['Fecha inicio', 'Región Comercial_Act 2026', 'Nombre UO', 'Jefatura_y', 'Ruta', 'Hora de llegada'],
    ascending=[True, True, True, True, True, True]
).reset_index(drop=True)

# 📊 Resultado final
df_filtrado

,Región Comercial_Act 2026,Nombre UO,Jefatura_y,Ruta,Descripción Tipo,Id cliente,Cliente_x,Recurrencia Digital,Canal,GEC,Fecha inicio,Distancia de llegada al cliente (mts),Distancia de salida al cliente (mts),Hora de llegada,Hora de salida,Fuera de frecuencia,Geoeficiencia,Geoefectividad,Tiempo de atencion,Pedido Digital
0,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,1920104041,MISC. TODO AMERICANO,Si,ABARROTES Y MISCELANEAS,PLATA,2025-10-01,8.993612,8.993612,12:58:05,12:58:08,0,1,0,00:00:03,0
1,Acapulco,Cayaco,CJ1,CJ0106,Preventa Comercial,1920009185,Misc Ramses Aldair,Si,ABARROTES Y MISCELANEAS,ORO,2025-10-01,3.214962,34.875740,16:14:04,16:16:37,0,1,1,00:02:33,0
2,Acapulco,Cayaco,CJ2,CJ0038,Preventa Comercial,1920000085,MISC EL PUENTE,Si,ABARROTES Y MISCELANEAS,PLATA,2025-10-01,258.157104,16.318970,10:43:12,10:44:23,0,0,0,00:01:11,1
3,Acapulco,Cayaco,CJ2,CJ0039,Preventa Comercial,1920000009,Misc El Apipilulteco,Si,ABARROTES Y MISCELANEAS,ORO,2025-10-01,17.903564,17.903564,16:45:08,16:45:13,0,1,0,00:01:13,0
4,Acapulco,Cayaco,CJ2,CJ0040,Preventa Comercial,1920110495,Misc Lulu,Si,ABARROTES Y MISCELANEAS,ORO,2025-10-01,8.093121,8.093121,14:15:57,14:16:07,0,1,0,00:00:10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5370,Tecamachalco,Tecamachalco,NA2,NA0074,Preventa Comercial,520331893,9 SUR,Si,HOGAR CON VENTA,BRONCE,2025-11-12,3.307659,53.713875,14:00:51,14:01:32,0,0,0,00:00:41,0
5371,Tecamachalco,Tecamachalco,NA6,NA0004,Preventa Comercial,501810555,PARELERIA Y ABARROTES LA ESPER,Si,ABARROTES Y MISCELANEAS,PLATA,2025-11-12,5.652928,8.126591,11:19:20,11:26:31,0,1,1,00:07:11,0
5372,Tecamachalco,Tecamachalco,NA6,NA0004,Preventa Comercial,520009141,TIENDA TANIROSS,Si,HOGAR CON VENTA,PLATA,2025-11-12,12.170732,4.925267,13:10:57,13:13:58,0,1,1,00:03:01,0
5373,Tecamachalco,Tecamachalco,NA6,NA0374,Preventa Comercial,520282972,LA GUERA,Si,BEBIDAS ALCOHOLICAS,PLATA,2025-11-12,15.826622,15.826622,14:41:13,14:41:26,0,1,0,00:00:13,1
5374,Tecamachalco,Tecamachalco,NA6,NAFA06,Farmer Comercial,501810555,PARELERIA Y ABARROTES LA ESPER,Si,ABARROTES Y MISCELANEAS,PLATA,2025-11-12,11.542014,11.542014,15:29:56,15:30:15,0,1,0,00:00:19,0

In [20]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

# 📁 Nombre del archivo de salida
ruta_salida = "Reporte_Recurrencia_Digital.xlsx"

# ✍️ Exportar a Excel (sin estilo)
df_filtrado.to_excel(ruta_salida, index=False, sheet_name="Recurrencia Digital")

# 📚 Cargar el archivo con openpyxl para aplicar estilo
wb = load_workbook(ruta_salida)
ws = wb.active

# 🎨 Estilos
header_fill = PatternFill(start_color="C00000", end_color="C00000", fill_type="solid")  # Rojo Coca-Cola
header_font = Font(color="FFFFFF", bold=True, name="Calibri", size=11)
center_align = Alignment(horizontal="center", vertical="center")
border_style = Border(
    left=Side(border_style="thin", color="D9D9D9"),
    right=Side(border_style="thin", color="D9D9D9"),
    top=Side(border_style="thin", color="D9D9D9"),
    bottom=Side(border_style="thin", color="D9D9D9"),
)

# 🧱 Aplicar formato a los encabezados
for cell in ws[1]:
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = center_align
    cell.border = border_style

# 📏 Ajustar ancho automático de columnas
for column_cells in ws.columns:
    length = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column_cells)
    adjusted_width = length + 2
    ws.column_dimensions[column_cells[0].column_letter].width = adjusted_width

# ❄️ Congelar la fila de encabezado
ws.freeze_panes = "A2"

# 💾 Guardar el archivo final
wb.save(ruta_salida)

print(f"✅ Reporte generado con formato ejecutivo: {ruta_salida}")

✅ Reporte generado con formato ejecutivo: Reporte_Recurrencia_Digital.xlsx