In [1]:
import streamlit as st
import pandas as pd
import pydeck as pdk
import hashlib
import glob
import streamlit.components.v1 as components
import plotly.graph_objects as go
import matplotlib.colors as mcolors

In [2]:
# 📂 Ruta donde están los archivos
ruta_archivos = "reportes_clientes/*.xlsx"

# 🧾 Lista de todos los archivos que coincidan
archivos = glob.glob(ruta_archivos)

# 📊 Leer y concatenar todos los archivos (solo hoja 'Resumen ruta')
dfs = []

for archivo in archivos:
    try:
        df_temp = pd.read_excel(archivo, sheet_name="Reporte diario cliente")
        df_temp["Archivo"] = archivo  # opcional: para saber de qué archivo viene
        dfs.append(df_temp)
    except ValueError:
        print(f"⚠️ La hoja 'Resumen ruta' no se encontró en {archivo}")
    except Exception as e:
        print(f"❌ Error al leer {archivo}: {e}")

# Concatenar si hay data
if dfs:
    df_mrk = pd.concat(dfs, ignore_index=True)
    print("✅ Archivos combinados correctamente:", len(dfs))
else:
    print("⚠️ No se pudo leer ningún archivo válido.")

✅ Archivos combinados correctamente: 41

In [3]:
df_mrk

,Zona,Región,Gerencia,Jefatura,Ruta,Id cliente,Cliente,Canal,GEC,Fecha,...,Latitud del maestro,Longitud del maestro,Tiempo de atencion,Geoeficiencia fuera de frecuencia,Geoefectividad fuera de frecuencia,Fuera de frecuencia,Pedido Digital,Pedido Omnicanal,Planeado Digital,Archivo
0,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901029,ABTS HERRERA,ABARROTES Y MISCELANEAS,PLATA,2025-09-09,...,17.834357,-97.788940,00:17:49,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
1,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901031,MISC ERIKA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,18.018685,-97.896553,00:02:11,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
2,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901033,AGUSTIN SOSA LEZAMA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,18.019240,-97.898173,00:00:41,1,0,1,0,0,0,reportes_clientes/IndicadoresReport_2025-09-09...
3,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901034,SOSITA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-09,...,18.021135,-97.899470,00:12:45,1,1,0,1,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
4,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901041,MISC TONITO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-10,...,18.082260,-97.918300,00:01:01,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11251858,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0118,1950086095,MISCELANEA LOS ANGELES,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,16.911502,-99.802992,00:00:04,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-09-17...
11251859,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0093,1950086096,MISC NICO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,16.929762,-99.833150,00:05:55,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-17...
11251860,CENTRO-PACIFICO,COSTAS,HN01,HN2,HN0072,1950086106,ABARROTES EL LLANITO,HOGAR CON VENTA,BRONCE,2025-09-22,...,17.162812,-100.388523,00:06:24,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-17...
11251861,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0139,1950086116,DULCERIA SOL,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,17.563190,-99.505512,00:00:13,1,1,0,0,0,1,reportes_clientes/IndicadoresReport_2025-09-17...
11251862,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0140,1950086117,MISCELANEA REGIS,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,17.556077,-99.511316,00:05:05,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-17...

In [4]:
from datetime import time

# 🕒 1. Detectar columnas con "(hr)"
cols_hr = [col for col in df_mrk.columns if '(hr)' in col]
print("Columnas a convertir:", cols_hr)

# 🧭 2. Normalizar y convertir
for col in cols_hr:
    # Si algún valor es datetime.time, conviértelo a string "HH:MM:SS"
    df_mrk[col] = df_mrk[col].apply(
        lambda x: x.strftime('%H:%M:%S') if isinstance(x, time) else x
    )
    # Luego convertir a timedelta
    df_mrk[col] = pd.to_timedelta(df_mrk[col], errors='coerce')

# 📊 Verificar
df_mrk.info()

Columnas a convertir: []
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251863 entries, 0 to 11251862
Data columns (total 31 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   Zona                                   object
 1   Región                                 object
 2   Gerencia                               object
 3   Jefatura                               object
 4   Ruta                                   object
 5   Id cliente                             int64
 6   Cliente                                object
 7   Canal                                  object
 8   GEC                                    object
 9   Fecha                                  datetime64[ns]
 10  Pedido                                 int64
 11  Distancia de llegada al cliente (mts)  float64
 12  Distancia de salida al cliente (mts)   float64
 13  Hora de llegada                        object
 14  Hora de salida                         object
 15  Geoeficiencia                          int64
 16  Geoefectividad                         int64
 17  Latitud de entrada                     float64
 18  Longitud de entrada                    float64
 19  Latitud de salida                      float64
 20  Longitud de salida                     float64
 21  Latitud del maestro                    float64
 22  Longitud del maestro                   float64
 23  Tiempo de atencion                     object
 24  Geoeficiencia fuera de frecuencia      int64
 25  Geoefectividad fuera de frecuencia     int64
 26  Fuera de frecuencia                    int64
 27  Pedido Digital                         int64
 28  Pedido Omnicanal                       int64
 29  Planeado Digital                       int64
 30  Archivo                                object
dtypes: datetime64[ns](1), float64(8), int64(10), object(12)
memory usage: 2.6+ GB

In [5]:
df_mrk.head()

,Zona,Región,Gerencia,Jefatura,Ruta,Id cliente,Cliente,Canal,GEC,Fecha,...,Latitud del maestro,Longitud del maestro,Tiempo de atencion,Geoeficiencia fuera de frecuencia,Geoefectividad fuera de frecuencia,Fuera de frecuencia,Pedido Digital,Pedido Omnicanal,Planeado Digital,Archivo
0,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901029,ABTS HERRERA,ABARROTES Y MISCELANEAS,PLATA,2025-09-09,...,17.834357,-97.788940,00:17:49,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
1,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901031,MISC ERIKA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,18.018685,-97.896553,00:02:11,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
2,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901033,AGUSTIN SOSA LEZAMA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,18.019240,-97.898173,00:00:41,1,0,1,0,0,0,reportes_clientes/IndicadoresReport_2025-09-09...
3,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901034,SOSITA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-09,...,18.021135,-97.899470,00:12:45,1,1,0,1,1,1,reportes_clientes/IndicadoresReport_2025-09-09...
4,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901041,MISC TONITO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-10,...,18.082260,-97.918300,00:01:01,1,1,0,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...

In [6]:
df_catalogo = pd.read_csv('catalogo.csv', encoding='utf-8')
df_catalogo = df_catalogo[['Ruta','Jefatura','Tipo','Descripción Tipo','TPV','Región Comercial_Act 2026','Nombre UO']]

df_mrk_full = df_mrk.merge(how='left', right=df_catalogo, left_on='Ruta', right_on='Ruta')
df_mrk_full.head()

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente,Canal,GEC,Fecha,...,Pedido Digital,Pedido Omnicanal,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO
0,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901029,ABTS HERRERA,ABARROTES Y MISCELANEAS,PLATA,2025-09-09,...,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan
1,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901031,MISC ERIKA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan
2,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901033,AGUSTIN SOSA LEZAMA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,0,0,0,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan
3,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901034,SOSITA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-09,...,1,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan
4,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901041,MISC TONITO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-10,...,0,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan

In [7]:
df_mrk_cp = df_mrk_full[df_mrk_full['Zona'] == 'CENTRO-PACIFICO']
df_mrk_cp = df_mrk_cp[df_mrk_cp['Tipo'].isin(['PR', 'PCOP', 'FC', 'MA', 'PRTDC'])]
df_mrk_cp = df_mrk_cp.rename(columns={'Fecha': 'Fecha inicio'})

df_mrk_cp['Región'] = df_mrk_cp['Región'].where(
~df_mrk_cp['Tipo'].isin(['MA', 'PRTDC'])
).fillna(df_mrk_cp['Tipo'].replace({'MA': 'MAYORISTAS', 'PRTDC': 'MODERNO'}))
df_mrk_cp['Semana'] = df_mrk_cp['Fecha inicio'].dt.isocalendar().week

df_mrk_cp

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente,Canal,GEC,Fecha inicio,...,Pedido Omnicanal,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana
0,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901029,ABTS HERRERA,ABARROTES Y MISCELANEAS,PLATA,2025-09-09,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
1,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901031,MISC ERIKA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
2,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901033,AGUSTIN SOSA LEZAMA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,0,0,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
3,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901034,SOSITA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-09,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
4,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901041,MISC TONITO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-10,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11251858,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0118,1950086095,MISCELANEA LOS ANGELES,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,0,1,reportes_clientes/IndicadoresReport_2025-09-17...,HR1,PR,Preventa Comercial,ZPV,Acapulco,Renacimiento,39
11251859,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0093,1950086096,MISC NICO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,1,reportes_clientes/IndicadoresReport_2025-09-17...,HR1,PR,Preventa Comercial,ZPV,Acapulco,Renacimiento,39
11251860,CENTRO-PACIFICO,COSTAS,HN01,HN2,HN0072,1950086106,ABARROTES EL LLANITO,HOGAR CON VENTA,BRONCE,2025-09-22,...,1,1,reportes_clientes/IndicadoresReport_2025-09-17...,HN2,PR,Preventa Comercial,ZPV,Costas,Tecpan,39
11251861,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0139,1950086116,DULCERIA SOL,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,0,1,reportes_clientes/IndicadoresReport_2025-09-17...,HV2,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,39
11251862,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0140,1950086117,MISCELANEA REGIS,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,1,reportes_clientes/IndicadoresReport_2025-09-17...,HV2,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,39

In [8]:
df_mrk_cp['Tiempo de atencion'] = pd.to_timedelta(df_mrk_cp['Tiempo de atencion'], errors='coerce')
df_mrk_cp['Hora de llegada'] = pd.to_datetime(
    df_mrk_cp['Hora de llegada'], format='%H:%M:%S', errors='coerce'
)

# 📊 Crear el pivot con diferentes funciones de agregación
df_pivot_gec = df_mrk_cp.pivot_table(
    index=['Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','Fecha inicio','GEC'],
    aggfunc={
        'Id cliente': 'count',
        'Geoeficiencia': 'sum',
        'Geoefectividad': 'sum',
        'Tiempo de atencion': 'mean',
        'Hora de llegada': 'min',
        'Pedido Omnicanal': 'sum',
    }
)

# 🔹 Convertir timedelta a HH:MM:SS sin días ni decimales
#df_pivot_gec['Tiempo de atencion'] = df_pivot_gec['Tiempo de atencion'].apply(
#    lambda x: str(x).split(' days ')[-1].split('.')[0] if pd.notnull(x) else None
#)

# 🔹 Mostrar solo HH:MM:SS en la hora de llegada
df_pivot_gec['Hora de llegada'] = df_pivot_gec['Hora de llegada'].dt.strftime('%H:%M:%S')

df_pivot_gec

                                                                                                      Geoefectividad  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE                   15
                                                                                         CUSTOMIZADO               3
                                                                                         ORO                      11
                                                                                         PLATA                    18
                                                                            2025-01-03   BRONCE                    4
...                                                                                                              ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-01   CUSTOMIZADO               4
                                                                            2025-11-03   CUSTOMIZADO               8
                                                                            2025-11-04   CUSTOMIZADO               9
                                                                            2025-11-05   CUSTOMIZADO               6
                                                                            2025-11-06   CUSTOMIZADO               5

                                                                                                      Geoeficiencia  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE                  27
                                                                                         CUSTOMIZADO              4
                                                                                         ORO                     14
                                                                                         PLATA                   32
                                                                            2025-01-03   BRONCE                  30
...                                                                                                             ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-01   CUSTOMIZADO              4
                                                                            2025-11-03   CUSTOMIZADO             10
                                                                            2025-11-04   CUSTOMIZADO              9
                                                                            2025-11-05   CUSTOMIZADO              6
                                                                            2025-11-06   CUSTOMIZADO              6

                                                                                                     Hora de llegada  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE             10:37:28
                                                                                         CUSTOMIZADO        10:32:08
                                                                                         ORO                10:07:36
                                                                                         PLATA              10:47:29
                                                                            2025-01-03   BRONCE             08:27:25
...                                                                                                              ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-01   CUSTOMIZADO        07:44:28
                                                                            2025-11-03   CUSTOMIZADO        08:28:48
                                                                            2025-11-04   CUSTOMIZADO        08:07:33
                                                                            2025-11-05   CUSTOMIZADO        08:02:53
                                                                            2025-11-06   CUSTOMIZADO        08:38:22

                                                                                                      Id cliente  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE               29
                                                                                         CUSTOMIZADO           4
                                                                                         ORO                  15
                                                                                         PLATA                32
                                                                            2025-01-03   BRONCE               38
...                                                                                                          ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-01   CUSTOMIZADO           4
                                                                            2025-11-03   CUSTOMIZADO          10
                                                                            2025-11-04   CUSTOMIZADO           9
                                                                            2025-11-05   CUSTOMIZADO           9
                                                                            2025-11-06   CUSTOMIZADO           7

                                                                                                      Pedido Omnicanal  \
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE                     16
                                                                                         CUSTOMIZADO                 3
                                                                                         ORO                        12
                                                                                         PLATA                      20
                                                                            2025-01-03   BRONCE                      6
...                                                                                                                ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-01   CUSTOMIZADO                 4
                                                                            2025-11-03   CUSTOMIZADO                 9
                                                                            2025-11-04   CUSTOMIZADO                 9
                                                                            2025-11-05   CUSTOMIZADO                 9
                                                                            2025-11-06   CUSTOMIZADO                 7

                                                                                                            Tiempo de atencion
Región Comercial_Act 2026 Nombre UO    Jefatura_y Ruta   Descripción Tipo   Fecha inicio GEC
Acapulco                  Cayaco       CJ1        CJ0011 Preventa Comercial 2025-01-02   BRONCE      0 days 00:00:40.793103448
                                                                                         CUSTOMIZADO    0 days 00:01:15.750000
                                                                                         ORO         0 days 00:02:17.533333333
                                                                                         PLATA          0 days 00:01:15.875000
                                                                            2025-01-03   BRONCE      0 days 00:00:09.210526315
...                                                                                                                        ...
Tecamachalco              Tecamachalco NAB        NAM002 Asesor Mayorista   2025-11-01   CUSTOMIZADO    0 days 00:19:08.250000
                                                                            2025-11-03   CUSTOMIZADO    0 days 00:14:38.400000
                                                                            2025-11-04   CUSTOMIZADO 0 days 00:17:35.888888888
                                                                            2025-11-05   CUSTOMIZADO 0 days 00:15:07.111111111
                                                                            2025-11-06   CUSTOMIZADO 0 days 00:18:17.571428571

[659920 rows x 6 columns]

In [9]:
df_pivot_gec = df_pivot_gec.reset_index()
df_pivot_gec.info()
df_pivot_gec

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659920 entries, 0 to 659919
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Región Comercial_Act 2026  659920 non-null  object
 1   Nombre UO                  659920 non-null  object
 2   Jefatura_y                 659920 non-null  object
 3   Ruta                       659920 non-null  object
 4   Descripción Tipo           659920 non-null  object
 5   Fecha inicio               659920 non-null  datetime64[ns]
 6   GEC                        659920 non-null  object
 7   Geoefectividad             659920 non-null  int64
 8   Geoeficiencia              659920 non-null  int64
 9   Hora de llegada            659920 non-null  object
 10  Id cliente                 659920 non-null  int64
 11  Pedido Omnicanal           659920 non-null  int64
 12  Tiempo de atencion         659920 non-null  timedelta64[ns]
dtypes: datetime64[ns](1), int64(4), object(7), timedelta64[ns](1)
memory usage: 65.5+ MB

,Región Comercial_Act 2026,Nombre UO,Jefatura_y,Ruta,Descripción Tipo,Fecha inicio,GEC,Geoefectividad,Geoeficiencia,Hora de llegada,Id cliente,Pedido Omnicanal,Tiempo de atencion
0,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,BRONCE,15,27,10:37:28,29,16,0 days 00:00:40.793103448
1,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,CUSTOMIZADO,3,4,10:32:08,4,3,0 days 00:01:15.750000
2,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,ORO,11,14,10:07:36,15,12,0 days 00:02:17.533333333
3,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,PLATA,18,32,10:47:29,32,20,0 days 00:01:15.875000
4,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-03,BRONCE,4,30,08:27:25,38,6,0 days 00:00:09.210526315
...,...,...,...,...,...,...,...,...,...,...,...,...,...
659915,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-01,CUSTOMIZADO,4,4,07:44:28,4,4,0 days 00:19:08.250000
659916,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-03,CUSTOMIZADO,8,10,08:28:48,10,9,0 days 00:14:38.400000
659917,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-04,CUSTOMIZADO,9,9,08:07:33,9,9,0 days 00:17:35.888888888
659918,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-05,CUSTOMIZADO,6,6,08:02:53,9,9,0 days 00:15:07.111111111
659919,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-06,CUSTOMIZADO,5,6,08:38:22,7,7,0 days 00:18:17.571428571

In [10]:
df_final_cliente = df_pivot_gec[['Fecha inicio','Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','GEC','Id cliente','Geoeficiencia','Geoefectividad','Hora de llegada','Tiempo de atencion','Pedido Omnicanal']]

df_final_cliente = df_final_cliente.rename(columns={'Jefatura_y': 'Jefatura'})

df_final_cliente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659920 entries, 0 to 659919
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fecha inicio               659920 non-null  datetime64[ns]
 1   Región Comercial_Act 2026  659920 non-null  object
 2   Nombre UO                  659920 non-null  object
 3   Jefatura                   659920 non-null  object
 4   Ruta                       659920 non-null  object
 5   Descripción Tipo           659920 non-null  object
 6   GEC                        659920 non-null  object
 7   Id cliente                 659920 non-null  int64
 8   Geoeficiencia              659920 non-null  int64
 9   Geoefectividad             659920 non-null  int64
 10  Hora de llegada            659920 non-null  object
 11  Tiempo de atencion         659920 non-null  timedelta64[ns]
 12  Pedido Omnicanal           659920 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(7), timedelta64[ns](1)
memory usage: 65.5+ MB

In [11]:
df_final_cliente.to_parquet('bdd_mrk_cp_gec.parquet')

In [12]:
df_mrk_cp

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente,Canal,GEC,Fecha inicio,...,Pedido Omnicanal,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana
0,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901029,ABTS HERRERA,ABARROTES Y MISCELANEAS,PLATA,2025-09-09,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
1,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901031,MISC ERIKA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
2,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901033,AGUSTIN SOSA LEZAMA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,0,0,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
3,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901034,SOSITA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-09,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
4,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901041,MISC TONITO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-10,...,1,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11251858,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0118,1950086095,MISCELANEA LOS ANGELES,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,0,1,reportes_clientes/IndicadoresReport_2025-09-17...,HR1,PR,Preventa Comercial,ZPV,Acapulco,Renacimiento,39
11251859,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0093,1950086096,MISC NICO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,1,reportes_clientes/IndicadoresReport_2025-09-17...,HR1,PR,Preventa Comercial,ZPV,Acapulco,Renacimiento,39
11251860,CENTRO-PACIFICO,COSTAS,HN01,HN2,HN0072,1950086106,ABARROTES EL LLANITO,HOGAR CON VENTA,BRONCE,2025-09-22,...,1,1,reportes_clientes/IndicadoresReport_2025-09-17...,HN2,PR,Preventa Comercial,ZPV,Costas,Tecpan,39
11251861,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0139,1950086116,DULCERIA SOL,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,0,1,reportes_clientes/IndicadoresReport_2025-09-17...,HV2,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,39
11251862,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0140,1950086117,MISCELANEA REGIS,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,1,reportes_clientes/IndicadoresReport_2025-09-17...,HV2,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,39

In [13]:
df_class_clientes = pd.read_csv('Class_Clientes.csv', encoding='utf-8')
df_class_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cliente              444 non-null    int64
 1   Recurrencia Digital  444 non-null    object
dtypes: int64(1), object(1)
memory usage: 7.1+ KB

In [14]:
df_mrk_cp_class = df_mrk_cp.merge(how='left',right=df_class_clientes,left_on='Id cliente',right_on='Cliente')
df_mrk_cp_class = df_mrk_cp_class.drop(columns=['Cliente_y'])
df_mrk_cp_class['Recurrencia Digital'] = df_mrk_cp_class['Recurrencia Digital'].fillna("No")
df_mrk_cp_class

,Zona,Región,Gerencia,Jefatura_x,Ruta,Id cliente,Cliente_x,Canal,GEC,Fecha inicio,...,Planeado Digital,Archivo,Jefatura_y,Tipo,Descripción Tipo,TPV,Región Comercial_Act 2026,Nombre UO,Semana,Recurrencia Digital
0,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901029,ABTS HERRERA,ABARROTES Y MISCELANEAS,PLATA,2025-09-09,...,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37,No
1,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901031,MISC ERIKA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37,No
2,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901033,AGUSTIN SOSA LEZAMA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-11,...,0,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37,No
3,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901034,SOSITA,ABARROTES Y MISCELANEAS,BRONCE,2025-09-09,...,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37,No
4,CENTRO-PACIFICO,HUAJUAPAN,HJ01,HJ1,HJ0008,200901041,MISC TONITO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-10,...,1,reportes_clientes/IndicadoresReport_2025-09-09...,HJ1,PR,Preventa Comercial,ZPV,Huajuapan,Huajuapan,37,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11139594,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0118,1950086095,MISCELANEA LOS ANGELES,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,reportes_clientes/IndicadoresReport_2025-09-17...,HR1,PR,Preventa Comercial,ZPV,Acapulco,Renacimiento,39,No
11139595,CENTRO-PACIFICO,ACAPULCO,HR01,HR1,HR0093,1950086096,MISC NICO,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,reportes_clientes/IndicadoresReport_2025-09-17...,HR1,PR,Preventa Comercial,ZPV,Acapulco,Renacimiento,39,No
11139596,CENTRO-PACIFICO,COSTAS,HN01,HN2,HN0072,1950086106,ABARROTES EL LLANITO,HOGAR CON VENTA,BRONCE,2025-09-22,...,1,reportes_clientes/IndicadoresReport_2025-09-17...,HN2,PR,Preventa Comercial,ZPV,Costas,Tecpan,39,No
11139597,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0139,1950086116,DULCERIA SOL,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,reportes_clientes/IndicadoresReport_2025-09-17...,HV2,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,39,No
11139598,CENTRO-PACIFICO,CHILAPA-CHILPANCINGO,HV01,HV2,HV0140,1950086117,MISCELANEA REGIS,ABARROTES Y MISCELANEAS,BRONCE,2025-09-24,...,1,reportes_clientes/IndicadoresReport_2025-09-17...,HV2,PR,Preventa Comercial,ZPV,Chilapa-Chilpancingo,Chilpancingo,39,No

In [15]:
# 📊 Crear el pivot con diferentes funciones de agregación
df_pivot_class = df_mrk_cp_class.pivot_table(
    index=['Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','Fecha inicio','Recurrencia Digital'],
    aggfunc={
        'Id cliente': 'count',
        'Geoeficiencia': 'sum',
        'Geoefectividad': 'sum',
        'Tiempo de atencion': 'mean',
        'Hora de llegada': 'min',
        'Pedido Omnicanal': 'sum',
    }
)

# 🔹 Mostrar solo HH:MM:SS en la hora de llegada
df_pivot_class['Hora de llegada'] = df_pivot_class['Hora de llegada'].dt.strftime('%H:%M:%S')
df_pivot_class = df_pivot_class.reset_index()
df_pivot_class

,Región Comercial_Act 2026,Nombre UO,Jefatura_y,Ruta,Descripción Tipo,Fecha inicio,Recurrencia Digital,Geoefectividad,Geoeficiencia,Hora de llegada,Id cliente,Pedido Omnicanal,Tiempo de atencion
0,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,No,45,75,10:07:36,78,49,0 days 00:01:15.692307692
1,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-02,Si,2,2,12:29:44,2,2,0 days 00:00:36.500000
2,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-03,No,14,66,08:06:30,78,21,0 days 00:00:23.705128205
3,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-03,Si,0,1,08:07:05,2,1,0 days 00:01:56.500000
4,Acapulco,Cayaco,CJ1,CJ0011,Preventa Comercial,2025-01-04,No,34,55,08:50:54,57,39,0 days 00:01:13.280701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
237320,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-01,No,4,4,07:44:28,4,4,0 days 00:19:08.250000
237321,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-03,No,8,10,08:28:48,10,9,0 days 00:14:38.400000
237322,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-04,No,9,9,08:07:33,9,9,0 days 00:17:35.888888888
237323,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-05,No,6,6,08:02:53,9,9,0 days 00:15:07.111111111
237324,Tecamachalco,Tecamachalco,NAB,NAM002,Asesor Mayorista,2025-11-06,No,5,6,08:38:22,7,7,0 days 00:18:17.571428571

In [16]:
df_final_cliente_class = df_pivot_class[['Fecha inicio','Región Comercial_Act 2026','Nombre UO','Jefatura_y','Ruta','Descripción Tipo','Recurrencia Digital','Id cliente','Geoeficiencia','Geoefectividad','Hora de llegada','Tiempo de atencion','Pedido Omnicanal']]

df_final_cliente_class = df_final_cliente_class[df_final_cliente_class['Recurrencia Digital'] == 'Si']
df_final_cliente_class = df_final_cliente_class.rename(columns={'Jefatura_y': 'Jefatura'})

df_final_cliente_class.to_parquet('bdd_mrk_cp_class.parquet')

df_final_cliente_class.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29543 entries, 1 to 236799
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fecha inicio               29543 non-null  datetime64[ns]
 1   Región Comercial_Act 2026  29543 non-null  object
 2   Nombre UO                  29543 non-null  object
 3   Jefatura                   29543 non-null  object
 4   Ruta                       29543 non-null  object
 5   Descripción Tipo           29543 non-null  object
 6   Recurrencia Digital        29543 non-null  object
 7   Id cliente                 29543 non-null  int64
 8   Geoeficiencia              29543 non-null  int64
 9   Geoefectividad             29543 non-null  int64
 10  Hora de llegada            29543 non-null  object
 11  Tiempo de atencion         29543 non-null  timedelta64[ns]
 12  Pedido Omnicanal           29543 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(7), timedelta64[ns](1)
memory usage: 3.2+ MB